export enum ActionType {
  DUMMY_ACTION_0 = 'DUMMY_ACTION_0',
  DUMMY_ACTION_1 = 'DUMMY_ACTION_1',
  FETCH_WEATHER_START = 'FETCH_WEATHER_START',
  FETCH_WEATHER_COMPLETE = 'FETCH_WEATHER_COMPLETE',
  FETCH_WEATHER_FAIL = 'FETCH_WEATHER_FAIL',
}
